### ISSUE TITLE
`get_events_of` does not return event

### ISSUE THREAD

**Issue by mgravitt** [NostrDevKit/hello-nostr#1]
When publishing an event and immediately trying to retrieve it, I do not get any results. I believe it just sits on the `get_events_of` line. 

How do I changed it (code is currently pushed to this repo) to retrieve the event that was just submitted and then exit?

```rust
 let event = client.publish_text_note(message, &[]).await?;
    println!("{:#?}", event);

    let filter = Filter {
        ids: Some(vec![event.to_string()]),
        authors: None,
        kinds: None,
        events: None,
        pubkeys: None,
        hashtags: None,
        references: None,
        search: None,
        since: None,
        until: None,
        limit: None,
    };

    let events = client.get_events_of(vec![filter], None).await?;
    println!("{:#?}", events);
```

**Comment by yukibtc** [comment]
You forgot to call the `connect` method.
By the way, there was a bug: calling `event_id.to_string()` with `nip19` feature enabled, return the bech32 id instead of hex.
Now is fixed.

The last problem in this example is that rust execute everything very fast so when you call `get_events_of` the relay not found that event.
A solution is to put a `std::thread::sleep(...)` between `publish_text_note` and `get_events_of` (a second is sufficient).

The last thing, by default the `Client` not wait that an event is sent (for this in needed configure the `Client` with `Options`). Maybe is better to set by default that Client wait that an event is sent before continue, what do you think? 
I don't know what is the best solution. For example, in a client that listen continuosly for events is better to set this to off but in a CLI app that send only an event and that exit, is better to turn on that option.
I talking about this:

```rust
let opts = Options::new().wait_for_send(true);
let client = Client::new_with_opts(&my_keys, opts);
```

**Comment by yukibtc** [comment]
Should I set a default `sleep` in `get_events_of` and `req_events_of` methods?

**Comment by mgravitt** [comment]
I don't think having a default that sleeps is good. It would be better to just put it into the `hello-nostr` example and I can explain why it is there. 

I like the `wait_for_send` but I'm not sure if it would be used much outside of tutorials, so if I can solve it by putting in a sleep, I think that is best.
